articles/urls.py
from django.urls import path
from . import views

app_name = "articles_app"

urlpatterns = [
    path("", views.ArticleListView.as_view(), name="article_list"),
    path("<int:pk>/", views.ArticleDetailView.as_view(), name="article_detail"),
    path("delete/<int:pk>/", views.ArticleDeleteView.as_view(), name="article_delete"),
    path("edit/<int:pk>/", views.ArticleUpdateView.as_view(), name="article_edit"),
    path("new/", views.ArticleCreateView.as_view(), name="article_create")
]

news_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls")),
    path("users/", include('users.urls')),
    path("users/", include('django.contrib.auth.urls')),
    path("articles/", include("articles.urls")),
]

pages/urls.py
from django.urls import path 
from . import views
urlpatterns = [
    path("", views.HomePageView.as_view(), name="home")
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users_app'
urlpatterns = [
    path("signup", views.UserSignupView.as_view(), name="signup"),
]

articles/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=False)

    def get_absolute_url(self):
        return reverse("articles_app:article_detail", args=[str(self.pk)])

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    comment = models.TextField()
    commentator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("articles_app:article_detail", args=[str(self.pk)])

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
# Create your models here.


class CustomUser(AbstractUser):
    user_age = models.PositiveIntegerField(default=0)

    

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ['username', 'email']


class CustomUserChangeForm(UserChangeForm):
    
    class Meta(UserChangeForm.Meta):
        model = CustomUser
        fields = ['username', 'email']

articles/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from .models import Article
# Create your views here.


class ArticleListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = "article_list.html"
    context_object_name = "articles"
    login_url = "login"
 

class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = "article_detail.html"
    context_object_name = "article"
    login_url = "login"


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    fields = ('title', 'body')
    template_name = "article_update.html"
    success_url = reverse_lazy("articles_app:article_list")
    login_url = "login"


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    template_name = "article_delete.html"
    success_url = reverse_lazy("articles_app:article_list")
    login_url = "login"


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = "article_create.html"
    fields = ("title", "body")
    success_url = reverse_lazy("articles_app:article_list")
    login_url = "login"

    def form_valid(self, form):
        print(self.request.user)
        form.instance.author = self.request.user
        return super(ArticleCreateView, self).form_valid(form)

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class HomePageView(TemplateView):
    template_name = "home.html"

users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from . import forms
from django.urls import reverse_lazy
# Create your views here.


class UserSignupView(CreateView):
    form_class = forms.CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "signup.html"

templates/article_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Create Article
{% endblock title %}

{% block main_block %}
    <h1>Create New Article</h1>
    <form method="POST" class="mt-2">
        {% csrf_token %}
        {{form|crispy}} 
        <input type="submit" class="btn btn-warning" value="Create Article">
        <a href="{% url 'articles_app:article_list' %}" class="btn btn-primary ml-2">Cancel</a>
    </form>
{% endblock main_block %}

templates/article_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Delete Article
{% endblock title %}
{% block main_block %}
<br><br>
    <h1>Delete article</h1>
    <form method="POST" class="mt-2">
        {% csrf_token %}
        <h1>Are you sure you wanna delete {{article.title}} ??</h1>
        <br><br>
        <input type="submit" value="Confirm" class="btn btn-primary">
        <a href="{% url 'articles_app:article_list' %}" class="btn btn-primary ml-2">Cancel</a>
    </form>
{% endblock main_block %}

templates/article_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
{{article.title}}
{% endblock title %}

{% block main_block %}
    <div class="card border-primary mb-3 text-center mt-3" style="max-width: 18rem;">
        <div class="card-header">{{article.title}}</div>
        <div class="card-body text-primary">
          <p class="card-text">{{article.body}}</p>
        </div>
        <div class="card-footer">
            {% for comment in article.comments.all %}
                <h6 class="text-left">{{comment.commentator}} :</h6>
                <p class="text-left">{{comment.comment}}</p>
                Posted at {{comment.date}}
                <div class="dropdown-divider"></div>
            {% endfor %}
            <a href="{% url 'articles_app:article_edit' article.pk %}" class="btn btn-warning mt-2">Edit</a> 
            <a href="{% url 'articles_app:article_delete' article.pk %}"> <button class="btn btn-danger mt-2 ml-2">Delete</button></a>
            <a href="{% url 'articles_app:article_list' %}"> <button class="btn btn-primary mt-3 ml-2">All Articles</button></a>
        </div>
    </div>
{% endblock main_block %}

templates/article_list.html
{% extends 'base.html' %}
{% block title %}
Articles
{% endblock title %}

{% block main_block %}
    <br><br>
    {% for article in articles %}
    <div class="card border-primary mb-4">
        <div class="card-header bg-primary">
          <a href="{% url 'articles_app:article_detail' article.pk %} " style="text-decoration:none"><span><h4 class="card-title text-light">{{article.title}} </h4></span><span class="text-light">by {{article.author}} | {{article.date}}</span></a> 
        </div>
        <div class="card-body">
            <p class="card-text">{{article.body}}</p>
        </div>
        <div class="card-footer text-center">
           <a href="{% url 'articles_app:article_edit' article.pk %}"  class="btn btn-warning mr-5">Edit</a> 
           <a href="{% url 'articles_app:article_delete' article.pk %}"> <button class="btn btn-danger">Delete</button></a>
        </div>
    </div>
    {% endfor %}
{% endblock main_block %}

templates/article_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Update
{% endblock title %}

{% block main_block %}
    <h1>Update Blog</h1>
    <form method="POST" class="mt-2">
        {% csrf_token %}
        {{form|crispy}} 
        <input type="submit" class="btn btn-warning" value="Edit Article">
        <a href="{% url 'articles_app:article_list' %}" class="btn btn-primary ml-2">Cancel</a>
    </form>
{% endblock main_block %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{% block title %}Newspaper App{% endblock title %}</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
            <a class="navbar-brand" href="{% url 'home' %}">Newspaper</a>
            {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a href="{% url 'articles_app:article_create' %}" style="text-decoration:none">New Article</a></li>
                </ul>
            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{user.username}}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            </div>
                        </li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav ml-auto">
                        <a href="{% url 'login' %}" class="btn btn-success">Login</a>
                        <a href="{% url 'users_app:signup' %}" class="btn btn-warning ml-2">Signup</a>
                    </ul>   
                {% endif %}
            </div>
        </nav>
    <main>
        <div class="container">
            {% block main_block %}
            {% endblock main_block %}
        </div>   
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}
    Home
{% endblock title %}

{% block main_block %}
    <div class="jumbotron">
        <h1 class="display-4 mb-3">Welcome to the newspaper App</h1>
        <p class="lead">Handcrafted with Django and Bootsrap Basic Themes</p>
        <hr class="my-4">
        <a class="btn btn-primary btn-lg" href="{% url 'articles_app:article_list' %}" role="button">View all Articles</a>
    </div>
{% endblock main_block %}

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Signup 
{% endblock title %}

{% block main_block %}
    <br>
    <h2>Signup</h2>
    <br>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Signup" class="btn btn-success ml-2">
    </form>
    <br>
{% endblock main_block %}